name: Org Security Scan

on:
  workflow_call:
    inputs:
      run_branch:
        required: false
        type: string

jobs:
  sast-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # automatically uses system GITHUB_TOKEN, no need to pass it

      - name: Run SAST Scan
        run: echo "This is a placeholder for SAST/Secret scans"

  sca-dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # automatically uses system GITHUB_TOKEN

      - name: Run Dependabot (Dependency Review)
        uses: actions/dependency-review-action@v4
        with:
          - uses: actions/dependency-review-action@v4
  with:
    base_ref: main
    head_ref: ${{ github.ref_name }}

